### ISSUE TITLE
Make a stable release to be included in MELPA stable

### ISSUE THREAD

**Issue by matthewbauer** [nflath/sudo-edit#15]
Hi,

I've been using sudo-edit regularly now and it seems stable. Can you make a versioned release so that it can be included in the MELPA stable set?

**Comment by nflath** [comment]
Sure.  I'll try to get to this in the next week or so - If you have a patch that does it I'll merge it in sooner.

**Comment by nflath** [comment]
Are there instructions for how to do this?  Looking at https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md , it says:

To have a stable version generated for your package simply tag the repository using a naming compatible with version-to-list. The repo state of this tag will be used to generate the stable package.

But this is on 0.0.1, which is compatible to version-to-list?

**Comment by marsam** [comment]
I've created the tag v0.1.0, I think should be enough to be fetched for melpa stable
