### ISSUE TITLE
Can not edit files under FAT32

### ISSUE THREAD

**Issue by yuzumx** [nflath/sudo-edit#18]
Hello, Thank you for your work!

I encountered some minor problems when using: 
I unable to edit file under the ESP partition (file system is FAT32, user is root).

This is ERROR log:
```
Copying /tmp/tramp.430-FH.conf to /sudo:root@localhost:/boot/loader/entries/arch.conf...
Copying directly failed, see buffer ‘*tramp/sudo root@localhost*’ for details.
Copying /tmp/tramp.430-FH.conf to /sudo:root@localhost:/boot/loader/entries/arch.conf...failed
tramp-file-name-handler: Copying directly failed, see buffer ‘*tramp/sudo root@localhost*’ for details.
```

the `*tramp/sudo root@localhost*` buffer:
```
/boot/loader/entries/arch.conf
```

Thanks.

**Comment by marsam** [comment]
Hi, sorry for the late response, `sudo-edit` just uses TRAMP underneath, by the message looks like a problem with TRAMP. Would you mind [reporting it to upstream](https://www.gnu.org/software/emacs/draft/manual/html_node/tramp/Bug-Reports.html)?

**Comment by yuzumx** [comment]
Thank you for your reply!

I am very happy to report to the upstream, but I can not because I live in China, and can not connect to the GNU website ...

I am sorry……

**Comment by yuzumx** [comment]
I tried to report bugs to GNU Emacs in the correct way.

But they can't read... because of my poor English……

I'm sorry.

**Comment by blahgeek** [comment]
In case anyone is interested, I sent a bug report to the mailing list: https://lists.gnu.org/archive/html/tramp-devel/2020-12/msg00012.html
