### ISSUE TITLE
sudo-edit fails remotely if using scp

### ISSUE THREAD

**Issue by articuluxe** [nflath/sudo-edit#7]
I normally use the default "ssh" method to connect to remote servers.  Sometimes (using logic I am not familiar with, but based I think on file size), tramp will use "scp" instead.  

If I have a remote file open using tramp's "scp" method, AND
I am using sudo-edit's latest tramp-aware code in [#6](https://github.com/nflath/sudo-edit/pull/6), AND
I execute `sudo-edit` to open the file as root, I receive the error:

"Method `scp' is not supported for multi-hops."

(This is not a hard error, so I didn't know how to get a stack-trace using debug-on-error, sorry)

Note that before I executed `sudo-edit`, buffer-file-name evaluated to:

> /scp:user@host:/path/to/file

Whereas if I manually open the following path, it opens successfully as root:

> /ssh:user@host|sudo:root@host:/path/to/file

I propose changing "scp" to "ssh" when attempting sudo-edit.

**Comment by marsam** [comment]
I don't think this is possible. We would need to check in the all the hosts of the multi-hop chain which methods doesn't [support multi-hop](https://github.com/emacs-mirror/emacs/blob/6450714/lisp/net/tramp-sh.el#L4587-L4596) and provide a safe fallback, which is not possible because we don't know which methods (and with which parameters) are supported by each host.

> I propose changing "scp" to "ssh" when attempting sudo-edit.

This solution is incomplete, because:
- It assumes the `/ssh` with default parameters, which is not always the case.
- Doesn't handle a chain of multi-hops.

I think the tramp error "Method `xxx' is not supported for multi-hops." is sufficiently descriptive.

**Comment by nflath** [comment]
Yeah, I agree we shouldn't change the protocol to ssh from scp - presumably there's some reason they were using scp instead of ssh.

**Comment by articuluxe** [comment]
scp is merely the external transfer method (handling file transfers) associated with ssh inside tramp.  Tramp by default distinguishes the internal and external methods by filesize, which the user can control by customizing tramp-copy-size-limit.

I don't follow your specific objections.  
- why would it not handle a chain of multi-hops?  Each element in the chain, if using scp, will break.  The same logic applies to every element.  And the worst that happens is that it still fails, which is what it does today.
- tramp methods "ssh" and "scp" would have the same parameters controlled by tramp options.  The method name is always just the method name, isn't it?  Unless you are referring to the optional port (following #).  But in that case, "ssh" and "scp" would also share the same port.  Perhaps there are some setups I am not aware of that would break this assumption, but they would certainly not be the most common, I would think.  
- I don't think the tramp error is very user-friendly, 

But no worries, I will make changes locally to support this for myself.  

Thank you for your time.

For any future readers running into this, another viable solution could be to customize "tramp-default-method" to "ssh" (at least on UNIX, where suitable).  This prevents "scp" being used for any size file.  The tramp documentation suggests "scp" may be slower when opening and closing many small files.  On my LAN, "ssh" seemed faster in all cases, even larger files.  But I'm loathe to abandon "scp" altogether.

**Comment by marsam** [comment]
@danrharms I'm so sorry, I totally misundertood you. You are right about the `tramp-copy-size-limit` value.

To expand my first comment let's say you have a file openned with: `/custom:host:/path/to/file.txt`
I think the error `"Method 'custom' is not supported for multi-hops."`  is reasonable, but the ssh-related out-of-band methods are clearly an exception.

can you check #8 please

**Comment by nflath** [comment]
Fail enough.  I merged your pull request.
